# Generated by Django 5.2.1 on 2026-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="sms_sent",
            field=models.BooleanField(default=False),
        ),
    ]
