# Generated by Django 5.2.1 on 2026-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_emailaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaccount',
            options={},
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
