# Generated by Django 5.2.1 on 2026-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_emailaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'ordering': ['priority', 'sent_today']},
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
